### ISSUE TITLE
quest_template

### ISSUE THREAD

**Issue by ccrs** [jasperrietrae/SAI-Editor#39]
errors appear on quest links, seems like quest_template querys are not updated.

**Comment by Discover-** [comment]
Can you tell me exactly what changed? Big lack of time on my side.

**Comment by ccrs** [comment]
meh its just the table colum names

**Comment by Faq** [comment]
what version you use?

**Comment by Rushor** [comment]
is updated and fixed in https://github.com/Rushor/SAI-Editor https://github.com/Rushor/SAI-Editor/commit/40da9232b7ed0611a09b9240328aa6459659231a
