### ISSUE TITLE
Add missing events, actions and targets

### ISSUE THREAD

**Issue by jasperrietrae** [jasperrietrae/SAI-Editor#45]

**Comment by el-druida** [comment]
Please, update the editor with the new targets, actions and events :(

**Comment by Rushor** [comment]
or at least show me one easy example for implementing a new action/event/target. then i would try to open a pr for all the new action/targets/events :)

**Comment by el-druida** [comment]
Roger that XD
Events:
SMART_EVENT_COUNTER_SET

Actions:
SMART_ACTION_MOVE_OFFSET //Once upon a time it was called "move_rise" jaja
SMART_ACTION_RANDOM_SOUND
SMART_ACTION_SET_CORPSE_DELAY
SMART_ACTION_DISABLE_EVADE
SMART_ACTION_GO_SET_GO_STATE
SMART_ACTION_SET_CAN_FLY
SMART_ACTION_REMOVE_AURAS_BY_TYPE
SMART_ACTION_SET_SIGHT_DIST
SMART_ACTION_FLEE
SMART_ACTION_ADD_THREAT
SMART_ACTION_LOAD_EQUIPMENT
SMART_ACTION_TRIGGER_RANDOM_TIMED_EVENT
SMART_ACTION_REMOVE_ALL_GAMEOBJECTS
SMART_ACTION_STOP_MOTION
SMART_ACTION_PLAY_ANIMKIT
SMART_ACTION_END

Targets:
SMART_TARGET_FARTHEST
SMART_TARGET_LOOT_RECIPIENTS
SMART_TARGET_VEHICLE_ACCESSORY
SMART_TARGET_END

**Comment by Discover-** [comment]
I've done three out of the above list as examples, @Rushor. Code-wise they are all the same, the only difference is the parameters and what kind of search forms it requires. Look through existing implementations to find examples of pre-implemented events, actions and targets. That way you can probably figure it out (do a project-wide search for an event/action/target you want to base it off of).  

Besides that, you have to edit the SQLite file to contain the parameters, tooltips, etc. It's those three tables that are relevant:  
- event_type_information
- action_type_information
- target_type_information

Good luck! Let me know if I can help anywhere. 😄

**Comment by Rushor** [comment]
@jasperrietrae 3 years later...

I understood it! i know how to update the sqllite and the other now! thank you!

first commit here https://github.com/Rushor/SAI-Editor/commit/ec0b2f405c6f114da353e1ba1844a06908178e52

So everyone who wanna use this version - i'm going to update it soon!

**Comment by Faq** [comment]
Better later, than never :)

**Comment by Rushor** [comment]
More progress, now also contains taskbar addition to the most needed tc wikis (gameobject, creature, item, quest etc)

https://github.com/Rushor/SAI-Editor/commit/89b5fd3b35e57ef814aabea85779a6e32cf8eccb

**Comment by Rushor** [comment]
todo:

SMART_EVENT_SCENE_START              = 78,      // don't use on 3.3.5a
    SMART_EVENT_SCENE_TRIGGER            = 79,      // don't use on 3.3.5a
    SMART_EVENT_SCENE_CANCEL             = 80,      // don't use on 3.3.5a
    SMART_EVENT_SCENE_COMPLETE           = 81,      // don't use on 3.3.5a
    SMART_EVENT_SUMMONED_UNIT_DIES       = 82,      // CreatureId(0 all), CooldownMin, CooldownMax

//UNUSED_SMART_ACTION_SPAWN_SPAWNGROUP          = 131,    // Group ID, min secs, max secs, spawnflags (RESERVED, PENDING CHERRYPICK)
    //UNUSED_SMART_ACTION_DESPAWN_SPAWNGROUP        = 132,    // Group ID, min secs, max secs, spawnflags (RESERVED, PENDING CHERRYPICK)
    //UNUSED_SMART_ACTION_RESPAWN_BY_SPAWNID        = 133,    // spawnType, spawnId (RESERVED, PENDING CHERRYPICK)
    //SMART_ACTION_INVOKER_CAST                     = 134,    // spellID, castFlags
    SMART_ACTION_PLAY_CINEMATIC                     = 135,    // entry, cinematic
    SMART_ACTION_SET_MOVEMENT_SPEED                 = 136,    // movementType, speedInteger, speedFraction
    //UNUSED_SMART_ACTION_PLAY_SPELL_VISUAL_KIT     = 137,    // spellVisualKitId (RESERVED, PENDING CHERRYPICK)
    SMART_ACTION_OVERRIDE_LIGHT                     = 138,    // zoneId, lightId, fadeInTime
    SMART_ACTION_OVERRIDE_WEATHER                   = 139,    // zoneId, weatherId, weatherGrade

SMART_TARGET_FARTHEST                     = 28,   // maxDist, playerOnly, isInLos
    SMART_TARGET_VEHICLE_PASSENGER            = 29,   // seatMask (0 - all seats)
    SMART_TARGET_CLOSEST_UNSPAWNED_GAMEOBJECT = 30,   // entry(0any), maxDist

**Comment by Rushor** [comment]
All new SMART_ACTION_'s are now added :)

**Comment by Faq** [comment]
https://github.com/Rushor/SAI-Editor/commits/master
