### ISSUE TITLE
Phasemasks can't be used at all

### ISSUE THREAD

**Issue by BarbzYHOOL** [jasperrietrae/SAI-Editor#49]
Everytime you put a phasemask, and then select another line, it throws an error (4 errors in a row if you click "ok") and it's impossible to use phases at all o_0
This is an app-breaking issue, it blocks the user or he has to crash the application. And can never make phased mobs.

**Comment by Pondaveia** [comment]
You can actually use phases but if you generate comments then it screws up with all those errors
