### ISSUE TITLE
[Error] Cannot open SAI Editor

### ISSUE THREAD

**Issue by Rushor** [jasperrietrae/SAI-Editor#52]
A freind just reported, that the SAI Editor some times does not correctly starts.

Quote from him:

For some reason as soon as i run the exe, it shows in task manager and almost instantly closes, no error, no nothing, Antivirus is off.
1.5.0 works, that's the old one. 1.5.1 does not work.

Any ideas why it does not work? Maybe @Faq @FrancescoBorzi can help? :)

**Comment by Faq** [comment]
Just some times? Then it is hard to fix if can't reproduce. db server is on same pc or connecting remotely?

**Comment by Rushor** [comment]
Always, connection i will ask

**Comment by FrancescoBorzi** [comment]
@Rushor sorry I can't help you with this :(

**Comment by Rushor** [comment]
okay do you know maybe someone for it?

**Comment by FrancescoBorzi** [comment]
@Rushor I don't, but you can check Keira3 as an alternative: https://github.com/azerothcore/Keira3
